name = "sunnahskills"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "sunnahskills-admin-v2"
database_id = "fc0a958f-4bfe-487f-845f-bce49d4715d5"

[vars]
# Non-secret vars (set here for local dev / defaults)
SITE_URL = "http://localhost:8788"
EMAIL_FROM = "noreply@sunnahskills.pages.dev"
EMAIL_TO = "mysunnahskill@gmail.com"