name = "sunnahskills"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[site]
bucket = "./dist"
entry-point = "functions"

[env.production]
name = "sunnahskills-prod"

[env.staging]
name = "sunnahskills-staging" 